# Generated by Django 5.2.3 on 2025-06-10 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0002_consulta_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='email',
        ),
    ]
