name: Django CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: mikael
          POSTGRES_PASSWORD: chat
          POSTGRES_DB: lacrei_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for PostgreSQL
        run: |
          until pg_isready -h localhost -p 5432; do echo "Aguardando banco de dados..."; sleep 1; done

      - name: Run migrations
        env:
          DB_NAME: lacrei_db
          DB_USER: mikael
          DB_PASSWORD: chat
          DB_HOST: localhost
        run: |
          python manage.py migrate

      - name: Run tests
        env:
          DB_NAME: lacrei_db
          DB_USER: mikael
          DB_PASSWORD: chat
          DB_HOST: localhost
        run: |
          python manage.py test